apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 3Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /datastore
    server: 192.168.100.130
  persistentVolumeReclaimPolicy: Retain 
